// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    StIcon: typeof import('./components/icon/StIcon.vue')['default']
    StInput: typeof import('./components/input/StInput.vue')['default']
  }
}

export { }
